# Generated by Django 5.1.1 on 2024-10-11 18:48

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=20)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Confluence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=30)),
                (
                    "description",
                    models.TextField(blank=True, max_length=200, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EntryTrigger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=30)),
                (
                    "description",
                    models.TextField(blank=True, max_length=200, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ExitTrigger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=30)),
                (
                    "description",
                    models.TextField(blank=True, max_length=200, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ManagementStrategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=30)),
                (
                    "description",
                    models.TextField(blank=True, max_length=200, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "Management Strategies",
            },
        ),
        migrations.CreateModel(
            name="Ticker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Timeframe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="AccountTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Use positive values for Deposit, negative for Withdrawals",
                        max_digits=12,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="main.account",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ConfluenceOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=30)),
                (
                    "description",
                    models.TextField(blank=True, max_length=200, null=True),
                ),
                (
                    "confluence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.confluence",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[("LONG", "Long"), ("SHORT", "Short")], max_length=5
                    ),
                ),
                ("entered_at", models.DateTimeField()),
                ("entry_price", models.DecimalField(decimal_places=5, max_digits=12)),
                ("stop_price", models.DecimalField(decimal_places=5, max_digits=12)),
                ("target_price", models.DecimalField(decimal_places=5, max_digits=12)),
                ("exited_at", models.DateTimeField(blank=True, null=True)),
                (
                    "exit_price",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=12, null=True
                    ),
                ),
                (
                    "profit_loss",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The gross Profit/Loss on the trade in £. Do not include fees",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "fees",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The fees paid on the trade. Use negative numbers for costs.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("hit_original_target", models.BooleanField(blank=True, null=True)),
                (
                    "min_price_during_trade",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        help_text="The lowest price we reached during the trade length. Account for spread.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "max_price_during_trade",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        help_text="The highest price we reached during the trade length. Account for spread.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "entry_grade",
                    models.CharField(
                        blank=True,
                        choices=[("a", "A"), ("b", "B"), ("c", "C")],
                        help_text="Now that the trade has been exited. Objectively rate the entry",
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "exit_grade",
                    models.CharField(
                        blank=True,
                        choices=[("a", "A"), ("b", "B"), ("c", "C")],
                        help_text="Now that the trade has been exited. Objectively rate the exit",
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "planned_r",
                    models.GeneratedField(
                        db_persist=False,
                        expression=models.Case(
                            models.When(
                                models.Q(("direction__exact", "LONG")),
                                then=django.db.models.expressions.CombinedExpression(
                                    django.db.models.expressions.CombinedExpression(
                                        models.F("target_price"),
                                        "-",
                                        models.F("entry_price"),
                                    ),
                                    "/",
                                    django.db.models.expressions.CombinedExpression(
                                        models.F("entry_price"),
                                        "-",
                                        models.F("stop_price"),
                                    ),
                                ),
                            ),
                            models.When(
                                models.Q(("direction__exact", "SHORT")),
                                then=django.db.models.expressions.CombinedExpression(
                                    django.db.models.expressions.CombinedExpression(
                                        models.F("entry_price"),
                                        "-",
                                        models.F("target_price"),
                                    ),
                                    "/",
                                    django.db.models.expressions.CombinedExpression(
                                        models.F("stop_price"),
                                        "-",
                                        models.F("entry_price"),
                                    ),
                                ),
                            ),
                            default=None,
                            output_field=models.BooleanField(),
                        ),
                        output_field=models.DecimalField(
                            decimal_places=2, max_digits=4, null=True
                        ),
                    ),
                ),
                (
                    "actual_r",
                    models.GeneratedField(
                        db_persist=False,
                        expression=models.Case(
                            models.When(
                                models.Q(("direction__exact", "LONG")),
                                then=django.db.models.expressions.CombinedExpression(
                                    django.db.models.expressions.CombinedExpression(
                                        models.F("exit_price"),
                                        "-",
                                        models.F("entry_price"),
                                    ),
                                    "/",
                                    django.db.models.expressions.CombinedExpression(
                                        models.F("entry_price"),
                                        "-",
                                        models.F("stop_price"),
                                    ),
                                ),
                            ),
                            models.When(
                                models.Q(("direction__exact", "SHORT")),
                                then=django.db.models.expressions.CombinedExpression(
                                    django.db.models.expressions.CombinedExpression(
                                        models.F("entry_price"),
                                        "-",
                                        models.F("exit_price"),
                                    ),
                                    "/",
                                    django.db.models.expressions.CombinedExpression(
                                        models.F("stop_price"),
                                        "-",
                                        models.F("entry_price"),
                                    ),
                                ),
                            ),
                            default=0,
                            output_field=models.DecimalField(
                                decimal_places=2, max_digits=4, null=True
                            ),
                        ),
                        output_field=models.DecimalField(
                            decimal_places=2, max_digits=4, null=True
                        ),
                    ),
                ),
                (
                    "is_winner",
                    models.GeneratedField(
                        db_persist=False,
                        expression=models.Case(
                            models.When(
                                models.Q(("direction__exact", "LONG")),
                                then=models.Q(
                                    ("exit_price__gt", models.F("entry_price"))
                                ),
                            ),
                            models.When(
                                models.Q(("direction__exact", "SHORT")),
                                then=models.Q(
                                    ("exit_price__lt", models.F("entry_price"))
                                ),
                            ),
                            default=None,
                            output_field=models.BooleanField(),
                        ),
                        output_field=models.BooleanField(),
                    ),
                ),
                (
                    "mae_percent",
                    models.GeneratedField(
                        db_persist=False,
                        expression=models.Case(
                            models.When(
                                models.Q(
                                    ("direction__exact", "LONG"),
                                    ("min_price_during_trade__isnull", False),
                                ),
                                then=django.db.models.expressions.CombinedExpression(
                                    django.db.models.expressions.CombinedExpression(
                                        django.db.models.expressions.CombinedExpression(
                                            models.F("entry_price"),
                                            "-",
                                            models.F("min_price_during_trade"),
                                        ),
                                        "/",
                                        django.db.models.expressions.CombinedExpression(
                                            models.F("entry_price"),
                                            "-",
                                            models.F("stop_price"),
                                        ),
                                    ),
                                    "*",
                                    models.Value(100),
                                ),
                            ),
                            models.When(
                                models.Q(
                                    ("direction__exact", "SHORT"),
                                    ("max_price_during_trade__isnull", False),
                                ),
                                then=django.db.models.expressions.CombinedExpression(
                                    django.db.models.expressions.CombinedExpression(
                                        django.db.models.expressions.CombinedExpression(
                                            models.F("max_price_during_trade"),
                                            "-",
                                            models.F("entry_price"),
                                        ),
                                        "/",
                                        django.db.models.expressions.CombinedExpression(
                                            models.F("stop_price"),
                                            "-",
                                            models.F("entry_price"),
                                        ),
                                    ),
                                    "*",
                                    models.Value(100),
                                ),
                            ),
                            default=None,
                            output_field=models.BooleanField(),
                        ),
                        output_field=models.DecimalField(
                            decimal_places=2, max_digits=4, null=True
                        ),
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to="main.account",
                    ),
                ),
                (
                    "confluences",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="trades",
                        to="main.confluenceoption",
                    ),
                ),
                (
                    "entry_trigger",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trades",
                        to="main.entrytrigger",
                    ),
                ),
                (
                    "exit_trigger",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trades",
                        to="main.exittrigger",
                    ),
                ),
                (
                    "management_strategy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trades",
                        to="main.managementstrategy",
                    ),
                ),
                (
                    "ticker",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trades",
                        to="main.ticker",
                    ),
                ),
                (
                    "trigger_timeframe",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trades",
                        to="main.timeframe",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("direction__iexact", "SHORT"),
                            ("entry_price__gt", models.F("stop_price")),
                            _connector="OR",
                        ),
                        name="check_valid_long_entry_and_stop_price",
                        violation_error_message="Entry price must be greater than stop loss price",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("direction__iexact", "SHORT"),
                            ("target_price__gt", models.F("entry_price")),
                            _connector="OR",
                        ),
                        name="check_valid_long_entry_and_target_price",
                        violation_error_message="Target price must be greater than entry price",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("direction__iexact", "LONG"),
                            ("entry_price__lt", models.F("stop_price")),
                            _connector="OR",
                        ),
                        name="check_valid_short_entry_and_stop_price",
                        violation_error_message="Entry price must be less than stop loss price",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("direction__iexact", "LONG"),
                            ("target_price__lt", models.F("entry_price")),
                            _connector="OR",
                        ),
                        name="check_valid_short_entry_and_target_price",
                        violation_error_message="Target price must be less than entry price",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("exit_price__isnull", True),
                                ("profit_loss__isnull", True),
                            ),
                            models.Q(
                                ("exit_price__isnull", False),
                                ("profit_loss__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="check_both_or_neither_exit_and_pnl_null",
                        violation_error_message="You must enter both Exit Price and Profit/Loss Amount",
                    ),
                ],
            },
        ),
    ]
