# Generated by Django 5.1.1 on 2024-10-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "long_short_flag",
                    models.TextField(choices=[("LONG", "Long"), ("SHORT", "Short")]),
                ),
                ("entry_price", models.FloatField()),
                ("exit_price", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
