# Generated by Django 5.1.1 on 2024-10-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trade",
            name="entry_grade",
            field=models.TextField(
                blank=True,
                choices=[("a", "A"), ("b", "B"), ("c", "C")],
                max_length=1,
                null=True,
            ),
        ),
    ]
