# Generated by Django 5.1.1 on 2024-10-06 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_trade_entry_grade"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Timeframe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name="trade",
            name="exit_grade",
            field=models.CharField(
                blank=True,
                choices=[("a", "A"), ("b", "B"), ("c", "C")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="stop_price",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trade",
            name="target_price",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trade",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="trade",
            name="entry_grade",
            field=models.CharField(
                blank=True,
                choices=[("a", "A"), ("b", "B"), ("c", "C")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="long_short_flag",
            field=models.CharField(
                choices=[("LONG", "Long"), ("SHORT", "Short")], max_length=5
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="ticker",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.ticker",
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="trigger_timeframe",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.timeframe",
            ),
        ),
    ]
