# Generated by Django 5.1.1 on 2024-10-11 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_entrystrategy"),
    ]

    operations = [
        migrations.AddField(
            model_name="trade",
            name="entry_strategy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.entrystrategy",
            ),
        ),
    ]
