# Generated by Django 5.1.1 on 2024-10-11 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_trade_entry_strategy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trade",
            name="entry_strategy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trades",
                to="main.entrystrategy",
            ),
        ),
    ]
