# Generated by Django 5.1.1 on 2024-10-06 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_ticker_timeframe_trade_exit_grade_trade_stop_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trade",
            name="entered_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 10, 6, 12, 0, 44, 583891)
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trade",
            name="exited_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 10, 6, 12, 0, 53, 659954)
            ),
            preserve_default=False,
        ),
    ]
