# Generated by Django 5.1.1 on 2024-10-11 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_trade_entry_strategy"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EntryStrategy",
            new_name="EntryTrigger",
        ),
        migrations.RenameField(
            model_name="trade",
            old_name="entry_strategy",
            new_name="entry_trigger",
        ),
    ]
