# Generated by Django 5.1.1 on 2024-10-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_trade_check_valid_entry_stop_price"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="trade",
            name="check_valid_long_prices",
        ),
        migrations.RemoveConstraint(
            model_name="trade",
            name="check_valid_entry_stop_price",
        ),
        migrations.AddConstraint(
            model_name="trade",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("long_short_flag__iexact", "SHORT"),
                    ("entry_price__gt", models.F("stop_price")),
                    _connector="OR",
                ),
                name="check_valid_long_entry_and_stop_price",
            ),
        ),
        migrations.AddConstraint(
            model_name="trade",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("long_short_flag__iexact", "SHORT"),
                    ("target_price__gt", models.F("entry_price")),
                    _connector="OR",
                ),
                name="check_valid_long_entry_and_target_price",
            ),
        ),
        migrations.AddConstraint(
            model_name="trade",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("long_short_flag__iexact", "LONG"),
                    ("entry_price__lt", models.F("stop_price")),
                    _connector="OR",
                ),
                name="check_valid_short_entry_and_stop_price",
            ),
        ),
        migrations.AddConstraint(
            model_name="trade",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("long_short_flag__iexact", "LONG"),
                    ("target_price__lt", models.F("entry_price")),
                    _connector="OR",
                ),
                name="check_valid_short_entry_and_target_price",
            ),
        ),
    ]
