# Generated by Django 5.1.1 on 2024-10-06 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_remove_trade_check_valid_long_entry_and_stop_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trade",
            name="ticker",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trades",
                to="main.ticker",
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="trigger_timeframe",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trades",
                to="main.timeframe",
            ),
        ),
    ]
