# Generated by Django 5.1.1 on 2024-10-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_alter_trade_ticker_alter_trade_trigger_timeframe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trade",
            name="exit_price",
            field=models.DecimalField(
                blank=True, decimal_places=5, max_digits=12, null=True
            ),
        ),
    ]
